//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RSSMotorCtrl.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_RSSMOTORCTRL_DIALOG         102
#define IDR_MAINFRAME                   128
#define IDC_STATIC_RAMP                 1000
#define IDC_STATIC_VEL                  1001
#define IDC_STATIC_RAMP_UPPERPOS        1002
#define IDC_STATIC_RAMP_INITIALPOS      1003
#define IDC_STATIC_RAMP_LOWERPOS        1004
#define IDC_STATIC_RAMP_MAXVEL          1005
#define IDC_STATIC_RAMP_MAXACC          1006
#define IDC_EDIT_RAMP_UPPERPOS          1007
#define IDC_EDIT_RAMP_INITIALPOS        1008
#define IDC_EDIT_RAMP                   1008
#define IDC_EDIT_RAMP_LOWERPOS          1009
#define IDC_EDIT_RAMP_MAXVEL            1010
#define IDC_EDIT_RAMP_MAXACC            1011
#define IDC_STATIC_RAMP_DELAY           1012
#define IDC_EDIT_RAMP_DELAY             1013
#define IDC_STATIC_RAMP_STATE           1014
#define IDC_STATIC_RAMP_STATEVALUE      1015
#define IDC_STATIC_RAMP_INFO            1016
#define IDC_BUTTON_RAMP_SEND            1017
#define IDC_BUTTON_RAMP_STARTLOOP       1018
#define IDC_STATIC_VEL_VEL              1019
#define IDC_STATIC_VEL_ACC              1020
#define IDC_STATIC_VEL_VEL_DEG_S        1021
#define IDC_STATIC_VEL_VEL_RPM          1022
#define IDC_SLIDER_VEL_VEL              1023
#define IDC_STATIC_VEL_ACC_DEG_S2       1024
#define IDC_SLIDER_VEL_ACC              1025
#define IDC_EDIT_VEL_VEL_DEG_S          1026
#define IDC_EDIT_VEL_VEL_RPM            1027
#define IDC_EDIT_VEL_ACC_DEG_S2         1028
#define IDC_BUTTON_VEL_SET_VEL          1029
#define IDC_BUTTON_VEL_SET_VEL_RPM      1030
#define IDC_BUTTON_VEL_SET_VEL_ACC      1031
#define IDC_CHECK_VEL_ALL               1032
#define IDC_STATIC_PARAM                1032
#define IDC_BUTTON_VEL_START            1033
#define IDC_STATIC_RAMP2                1034
#define IDC_STATIC_PARAM_ACTUAL         1035
#define IDC_STATIC_PARAM_TARGET         1036
#define IDC_STATIC_PARAM_MAX            1037
#define IDC_STATIC_PARAM_MIN            1037
#define IDC_STATIC_PARAM_VEL            1038
#define IDC_STATIC_PARAM_ACC            1039
#define IDC_STATIC_PARAM_POS            1040
#define IDC_STATIC_PARAM_T              1041
#define IDC_EDIT_PARAM_POS_ACT          1042
#define IDC_STATIC_DEV_STATUS           1042
#define IDC_EPA1                        1043
#define IDC_EPA2                        1044
#define IDC_EPA3                        1045
#define IDC_EPA4                        1046
#define IDC_EPA5                        1047
#define IDC_EPA6                        1048
#define IDC_EDIT_PARAM_POS_TARGET       1049
#define IDC_EPTARGET1                   1050
#define IDC_EPTARGET2                   1051
#define IDC_EPTARGET3                   1052
#define IDC_EPTARGET4                   1053
#define IDC_EPTARGET5                   1054
#define IDC_EPTARGET6                   1055
#define IDC_EDIT_PARAM_POS_MAX          1056
#define IDC_EPMIN1                      1057
#define IDC_EPMIN2                      1058
#define IDC_EPMIN3                      1059
#define IDC_EPMIN4                      1060
#define IDC_EPMIN5                      1061
#define IDC_EPMIN6                      1062
#define IDC_EDIT_PARAM_VEL_ACT          1063
#define IDC_EDIT_PARAM_VEL_TARGET       1064
#define IDC_EDIT_PARAM_VEL_MAX          1065
#define IDC_EDIT_PARAM_ACC_ACT          1066
#define IDC_EDIT_PARAM_ACC_TARGET       1067
#define IDC_EDIT_PARAM_ACC_MAX          1068
#define IDC_EDIT_PARAM_T_ACT            1069
#define IDC_EDIT_PARAM_T_TARGET         1070
#define IDC_EDIT_PARAM_ACC_MAX2         1071
#define IDC_EDIT_PARAM_T_ACT2           1071
#define IDC_EDIT_DEV_STATUS             1071
#define IDC_EDIT_PARAM_T_MAX            1072
#define IDC_STATIC_REC                  1073
#define IDC_EDIT_REC_FILENAME           1074
#define IDC_BUTTON_REC_DATA             1075
#define IDC_BUTTON_REC_T                1076
#define IDC_MFCLINK_REC_SELFILE         1077
#define IDC_STATIC_PARAM_MAX2           1078
#define IDC_EDIT_REC_TIME               1079
#define IDC_STATIC_PARAM_VELM           1080
#define IDC_STATIC_PARAM_ACCM           1081
#define IDC_STATIC_PARAM_POSM           1082
#define IDC_EDIT_PARAM_POS_TARGETM      1083
#define IDC_EDIT_PARAM_POS_MAXM         1084
#define IDC_EDIT_PARAM_VEL_TARGETM      1085
#define IDC_EDIT_PARAM_VEL_MAXM         1086
#define IDC_EDIT_PARAM_ACC_ACTM         1087
#define IDC_EDIT_PARAM_ACC_TARGETM      1088
#define IDC_EDIT_PARAM_ACC_MAXM         1089
#define IDC_MFCLINK_REC_SELFOLDER       1090
#define IDC_EDIT_PARAM_T_MAX2           1091
#define IDC_EDIT_PARAM_ACC_MAXM2        1092
#define IDC_EPMAX1                      1093
#define IDC_EPMAX2                      1094
#define IDC_EPMAX3                      1095
#define IDC_EPMAX4                      1096
#define IDC_EPMAX5                      1097
#define IDC_EPMAX6                      1098

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1059
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
